### ISSUE TITLE
Error on import in Python (No module named 'ezc3d._ezc3d')

### ISSUE THREAD

**Issue by melund** [pyomeca/ezc3d#35]
I have installed the package from conda `conda install -c pyomeca ezc3d`. 

But I get the following traceback on import: 

```python
>>> import ezc3d
Traceback (most recent call last):
  File "C:\Users\mel\anaconda3\lib\site-packages\ezc3d\ezc3d.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\mel\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ezc3d._ezc3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mel\anaconda3\lib\site-packages\ezc3d\__init__.py", line 3, in <module>
    from . import ezc3d
  File "C:\Users\mel\anaconda3\lib\site-packages\ezc3d\ezc3d.py", line 17, in <module>
    _ezc3d = swig_import_helper()
  File "C:\Users\mel\anaconda3\lib\site-packages\ezc3d\ezc3d.py", line 16, in swig_import_helper
    return importlib.import_module('_ezc3d')
  File "C:\Users\mel\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified module could not be found.
>>>
```

**Comment by melund** [comment]
It seems the windows recipe is wrong. It installs the library files to an incorrect prefix. 

on windows cmake should have: 
```
-DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%"^
```

**Comment by pariterre** [comment]
Ok! 

I was struggling on where to put stuff. I'll have a try why %LIBRARY_PREFIX%! 
Give me an 2 or 3 hours :) 

Thanks!

**Comment by melund** [comment]
No problem. I have created a conda-forge package with ezc3d. It works, but I ran into some problems on mac, though. So osx packages are skipped for now.

https://github.com/conda-forge/ezc3d-feedstock

Thanks for ezc3d. It was seriously needed. Was seriously considering forking btk to update it with python 3 support.

**Comment by pariterre** [comment]
Nice! 
Thx! 

Yep, I've figured that I would not be alone to want a better c3d file manager. Hope this will suit your needs! If you have any improvement to propose, feel free to ask or even PR :)

What is the error on Mac? I've tested it in the past and it was working...

**Comment by melund** [comment]
Here the final error I got before giving up:

https://github.com/conda-forge/staged-recipes/pull/7505#issuecomment-451847636

**Comment by pariterre** [comment]
Oh.. It seems something went wrong in linking.. I'll have a try within the next days with an actual Mac to see if it is a conda-build linking problem or an error in the CMake.

**Comment by pariterre** [comment]
Hi Melund!
Sorry for the delay... I actually struggle to find a Mac that I could install everything I wanted on! I've solved the linking problem, thus Mac recipe should now be able to work! :)
