### ISSUE TITLE
Error writing c3d file in Python

### ISSUE THREAD

**Issue by melund** [pyomeca/ezc3d#36]
I got the following traceback.

```
Traceback (most recent call last):
  File "extract-c3d-file.py", line 130, in <module>
    c3dobj.write(str(c3dfile_new))
  File "C:\Users\mel\anaconda3\lib\site-packages\ezc3d\__init__.py", line 174, in write
    self._storage['parameters']['POINT']['RATE']['value'][0]
TypeError: 'tuple' object does not support item assignment
```

**Comment by pariterre** [comment]
PR accepted, thanks for the changes
